name: Continuous Training
on:
  push:
    branches:
      - workflow_continuous_training
  #schedule:
  #  - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: Why to run this?
        required: false
        default: running CT
permissions:
  id-token:write
  contents:write
  pull-requests:write 
  issues:read
  packages:none
jobs:
  continuous-training:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.6"
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Train model
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: |
          pip3 install pipenv
          pipenv install -r requirements.txt
          export GOOGLE_APPLICATION_CREDENTIALS=$(python utilities/setter.py)
          pipenv run dvc pull model/model.pkl -r model-track
          pipenv run dvc unprotect model/model.pkl
          pipenv run dvc repro -f
          echo "Training completed"
          pipenv run dvc add model/model.pkl --to-remote -r model-track
          pipenv run dvc push model/model.pkl -r model-track
      - name: Commit .dvc file changes
        run: |
          git config --local user.email "tomas.pucutay@gmail.com"
          git config --local user.name "github-actions[bot]"
          git add model/model.pkl.dvc
          git commit -m "Updating model serialization"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - uses: iterative/setup-cml@v1
      - name: Push metrics
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat report.txt >> report.md
          cml-publish prediction_behaviour.png --md >> report.md
          cml-send-comment report.md